---
  # This playbook will be executed on boxA.
- name: Set up networking
  hosts: all
  become: yes
  vars:
    image: christianb93/networking
  tasks:
  - name: Install Open vswitch and Docker
    apt:
      name: "{{ item }}"
      update_cache: yes
      force_apt_get: yes
    loop:
      - openvswitch-switch
      - docker.io
      - python3-pip
  - name: Install docker module
    shell:
      pip3 install docker
  # We will now bring up an NGINX container called web1, create a virtual
  # VETH pair and move one part into the container
  - name: Start a docker container
    docker_container:
      auto_remove: yes
      detach: yes
      image: "{{ image }}"
      name: web1
      network_mode: none
      state: started
    register: docker_out
  - name: Capture PID of container
    set_fact:
      web1PID: "{{ docker_out.ansible_facts.docker_container.State.Pid }}"
  - name: See whether VETH device exists
    stat:
      path: /sys/devices/virtual/net/web1_veth1
    register: veth_stat_results
  - name: Delete VETH device if it exists
    shell: |
      ip link del web1_veth1
    when: veth_stat_results.stat.exists == True
  - name: Create VETH pair for container web1
    shell: |
      ip link add web1_veth0 type veth peer name web1_veth1
  - name: Move web1_veth0 into container namespace
    shell: |
      ip link set web1_veth0 netns {{ web1PID }}

  # Repeat the entire process for a second container - of course this could
  # be moved into a role in a later iteration
  - name: Start a docker container
    docker_container:
      auto_remove: yes
      detach: yes
      image: "{{ image }}"
      name: web2
      network_mode: none
      state: started
    register: docker_out
  - name: Capture PID of container
    set_fact:
      web2PID: "{{ docker_out.ansible_facts.docker_container.State.Pid }}"
  - name: See whether VETH device exists
    stat:
      path: /sys/devices/virtual/net/web2_veth1
    register: veth_stat_results
    # To make the script idempotent, we delete the
    # VETH device if it has already been created
  - name: Delete VETH device if it exists
    shell: |
      ip link del web2_veth1
    when: veth_stat_results.stat.exists == True
  - name: Create VETH pair for container web1
    shell: |
      ip link add web2_veth0 type veth peer name web2_veth1
  - name: Move web2_veth0 into container namespace
    shell: |
      ip link set web2_veth0 netns {{ web2PID }}


  # Now set set up the actual bridge and add the two
  # VETH interfaces. We use the OVS module, if we wanted to do
  # this manually, we would need to run
  # ovs-vsctl --if-exists del-br myBridge
  # ovs-vsctl add-br myBridge -- add-port myBridge web1_veth1 -- add-port myBridge web2_veth1
  - name: Create OVS bridge myBridge
    openvswitch_bridge:
      bridge: myBridge
      state: present
  - name: Add ports to bridge
    openvswitch_port:
      bridge: myBridge
      port: "{{ item }}"
      state: present
    loop:
      - web1_veth1
      - web2_veth1

  # Assign IP address to both veth endpoints and bring all devices up
  - name: Assign IP addresses and bring up devices
    shell: |
      nsenter -t {{ web1PID }} -n ip addr add  172.16.0.1/12 dev web1_veth0
      nsenter -t {{ web1PID }} -n ip link set web1_veth0 up
      ip link set web1_veth1 up
      nsenter -t {{ web2PID }} -n ip addr add  172.16.0.2/12 dev web2_veth0
      nsenter -t {{ web2PID }} -n ip link set web2_veth0 up
      ip link set web2_veth1 up


  # Finally we add a VXLAN port to establish a tunnel via the enp0s8 device
  # This corresponds to the command
  # ovs-vsctl add-port myBridge vxlan0 -- set interface vxlan0 type=vxlan options:remote_ip=192.168.50.5  options:dst_port=4789 options:ttl=5
  - name: Add VXLAN port vxlan0
    openvswitch_port:
      bridge: myBridge
      state: present
      port: vxlan0
      set: "interface vxlan0 type=vxlan options:remote_ip=192.168.50.5  options:dst_port=4789 options:ttl=5"
