# -*- mode: ruby -*-
# vi: set ft=ruby :

# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      0.0.1


servers=[
  {
    :define => "Lab04 - box1",
    :hostname => "box1",
    :ip => "192.168.50.4",
    :box => "ubuntu/focal64",
    :ram => 2048,
    :cpu => 1
  },
  {
    :define => "Lab04 - box2",
    :hostname => "box2",
    :ip => "192.168.50.5",
    :box => "ubuntu/focal64",
    :ram => 2048,
    :cpu => 1
  }
]

Vagrant.require_version ">= 2.2.6"

Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:define] do |node|
            # define the virtual machine
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]

            # configure virtual machine
            node.vm.provider "virtualbox" do |vb|
                vb.gui = false                                             # true = GUI, false = headless
                vb.customize ["modifyvm", :id, "--cpus", machine[:cpu]]    # number of cpu allocated
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]  # ram memory allocated
            end

            # configure virtual network
            node.vm.network "private_network", ip: machine[:ip], virtualbox__intnet: "myNetwork"

            # update linux packages currently within virtual machine
            node.vm.provision "shell", name: "update linux packages (as root)",
                run: "always", inline: "apt-get -y update && apt-get -y dist-upgrade"

            # install networking tools used within virtual machine
            node.vm.provision "shell", name: "install networking tools used in labs (as root)",
                run: "once", path: "../scripts/net-tools.sh"
        end
    end
end




#Vagrant.require_version ">= 2.2.6"

#Vagrant.configure("2") do |config|

  #N = 2                                                 # number of virtual machines to be created
  #(1..N).each do |machine_id|
    ## define the virtual machine
    #config.vm.define "Lab04 - box#{machine_id}"         # description
    #config.vm.box = "ubuntu/focal64"                    # base box - ubuntu 20.04
    #config.vm.hostname = "box#{machine_id}.vm"          # set hostname

    ## configure virtual machine
    #config.vm.provider :virtualbox do |vb, override|
      #vb.gui = false                                    # true = GUI, false = headless
      #vb.customize ["modifyvm", :id, "--cpus", 1]       # number of cpu allocated
      #vb.customize ["modifyvm", :id, "--memory", 2048]  # ram memory allocated
    #end

    ## configure virtual network
    #config.vm.network "private_network", ip: "192.168.50.#{3+machine_id}", virtualbox__intnet: "myNetwork"

    ## update linux packages currently within virtual machine
    #config.vm.provision "shell", name: "update linux packages (as root)",
      #run: "always", inline: "apt-get -y update && apt-get -y dist-upgrade"

    ## install networking tools used within virtual machine
    #config.vm.provision "shell", name: "install networking tools used in labs (as root)",
      #run: "once", path: "../scripts/net-tools.sh"
  #end
#end


#Vagrant.configure("2") do |config|

  ## We set up one machine, with a default NAT interface and a private network
  #config.vm.define "boxA" do |boxA|
    ##boxA.vm.box = "ubuntu/bionic64"
    #boxA.vm.box = "ubuntu/focal64"       # ubuntu 20.04 guest vm
    #boxA.vm.hostname = "boxA.vm"         # set hostname
    #boxA.vm.network "private_network", ip: "192.168.50.4", virtualbox__intnet: "myNetwork"
  #end

  ## and a second machine with a NAT interface and connected to the same private network
  #config.vm.define "boxB" do |boxB|
    ##boxB.vm.box = "ubuntu/bionic64"
    #boxB.vm.box = "ubuntu/focal64"       # ubuntu 20.04 guest vm
    #boxB.vm.hostname = "boxB.vm"         # set hostname
    #boxB.vm.network "private_network", ip: "192.168.50.5", virtualbox__intnet: "myNetwork"
  #end

#end
