---
  # This playbook will be executed on boxA.
- name: Set up networking
  hosts: all
  become: yes
  vars:
    image: christianb93/networking
  tasks:
  - name: Install Open vswitch and Docker
    apt:
      name: "{{ item }}"
      update_cache: yes
      force_apt_get: yes
    loop:
      - openvswitch-switch
      - docker.io
      - python3-pip
  - name: Install docker module
    shell:
      pip3 install docker
  # We will now bring up an NGINX container called web1, create a virtual
  # VETH pair and move one part into the container
  - name: Start a docker container
    docker_container:
      auto_remove: yes
      detach: yes
      image: "{{ image }}"
      name: web1
      network_mode: none
      state: started
    register: docker_out
  - name: Capture PID of container
    set_fact:
      web1PID: "{{ docker_out.ansible_facts.docker_container.State.Pid }}"
  - name: See whether VETH device exists
    stat:
      path: /sys/devices/virtual/net/web1_veth1
    register: veth_stat_results
  - name: Delete VETH device if it exists
    shell: |
      ip link del web1_veth1
    when: veth_stat_results.stat.exists == True
  - name: Create VETH pair for container web1
    shell: |
      ip link add web1_veth0 type veth peer name web1_veth1
  - name: Move web1_veth0 into container namespace
    shell: |
      ip link set web1_veth0 netns {{ web1PID }}

  # Repeat the entire process for a second container - of course this could
  # be moved into a role in a later iteration
  - name: Start a docker container
    docker_container:
      auto_remove: yes
      detach: yes
      image: "{{ image }}"
      name: web2
      network_mode: none
      state: started
    register: docker_out
  - name: Capture PID of container
    set_fact:
      web2PID: "{{ docker_out.ansible_facts.docker_container.State.Pid }}"
  - name: See whether VETH device exists
    stat:
      path: /sys/devices/virtual/net/web2_veth1
    register: veth_stat_results
    # To make the script idempotent, we delete the
    # VETH device if it has already been created
  - name: Delete VETH device if it exists
    shell: |
      ip link del web2_veth1
    when: veth_stat_results.stat.exists == True
  - name: Create VETH pair for container web1
    shell: |
      ip link add web2_veth0 type veth peer name web2_veth1
  - name: Move web2_veth0 into container namespace
    shell: |
      ip link set web2_veth0 netns {{ web2PID }}

  # Make sure that no IP address is assigned to enp0s8
  - name: Check IP address of enp0s8
    shell:
      ip addr show dev enp0s8  | grep 192.168 | awk 'FNR == 1 {print $2}'
    register:
      enp0s8
  - name: Delete IP address of enp0s8
    shell:
      ip addr del {{enp0s8.stdout}} dev enp0s8
    when: enp0s8.stdout != ""

  # Now we bring up our bridge and attach the ports
  - name: Create OVS bridge
    openvswitch_bridge:
      bridge: myBridge
      state: present
  - name: Add access ports to bridge
    openvswitch_port:
      bridge: myBridge
      port: "{{ item.interface }}"
      tag: "{{item.tag}}"
      state: present
    loop:
      - interface: web1_veth1
        tag: 100
      - interface: web2_veth1
        tag: 200
  - name: Add trunk port to bridge
    openvswitch_port:
      bridge: myBridge
      port: enp0s8
      state: present



  # Finally assign IP addresses to the inner VETH devices and bring up
  # all devices
  - name: Assign IP addresses
    shell: |
      nsenter -t {{ web1PID }} -n ip addr add  192.168.50.1/24 dev web1_veth0
      nsenter -t {{ web2PID }} -n ip addr add  192.168.60.2/24 dev web2_veth0
  - name: Bring up interfaces
    shell: |
      nsenter -t {{ web1PID }} -n ip link set  web1_veth0 up
      nsenter -t {{ web2PID }} -n ip link set  web2_veth0 up
      ip link set web1_veth1 up
      ip link set web2_veth1 up
