---
  # This playbook will be executed on boxC.
- name: Set up networking
  hosts: all
  become: yes
  tasks:
  - name: Install vlan package
    apt:
      update_cache: yes
      force_apt_get: yes
      state: latest
      name: vlan
  - name: See whether VLAN device exists
    stat:
      path: /sys/devices/virtual/net/enp0s8.200
    register: vlan_stat_results
    # To make the script idempotent, we delete the
    # VLAN device if it has already been created
  - name: Delete VLAN device if it exists
    shell: |
      vconfig rem enp0s8.200
    when: vlan_stat_results.stat.exists == True
  - name: Add VLAN device on enp0s8 with VLAN ID 200
    shell:
      vconfig add enp0s8 200
  - name: Assign IP address and bring device up
    shell: |
      ip addr add 192.168.70.6/24 dev enp0s8.200
      ip link set enp0s8.200 up
