# -*- mode: ruby -*-
# vi: set ft=ruby :

# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      0.0.1


Vagrant.configure("2") do |config|

  # set up one machine, with a default NAT interface and a host-only interface
  config.vm.define "boxA" do |boxA|
    #boxA.vm.box = "ubuntu/bionic64"
    boxA.vm.box = "ubuntu/focal64"       # ubuntu 20.04 guest vm
    boxA.vm.hostname = "boxA.vm"         # set hostname
    boxA.vm.network "private_network", ip: "192.168.50.4", :name => 'vboxnet0'
  end

  # setup a second machine with a NAT interface and again a host-only interface,
  # connected to the same network
  config.vm.define "boxB" do |boxB|
    #boxB.vm.box = "ubuntu/bionic64"
    boxB.vm.box = "ubuntu/focal64"       # ubuntu 20.04 guest vm
    boxB.vm.hostname = "boxB.vm"         # set hostname
    boxB.vm.network "private_network", ip: "192.168.50.5", :name => 'vboxnet0'
  end

end
